### ISSUE TITLE
为什么在Docker中添加了环境变量 API_KEY=xxxx 并没有生效？

### ISSUE THREAD

**Issue by LuckyZY** [mic1on/chatGPT-web#8]
根据项目中要求使用Docker命令-e API_KEY=xxxx添加密钥环境变量以后运行，发现API_KEY并没有生效，后台log日志如下：

``` bash
ChatGPT  | ValueError: API key is required
ChatGPT  | INFO:     192.168.80.100:34574 - "GET / HTTP/1.1" 200 OK
ChatGPT  | INFO:     192.168.80.100:34574 - "GET /credit_summary HTTP/1.1" 500 Internal Server Error
ChatGPT  | ERROR:    Exception in ASGI application
ChatGPT  | Traceback (most recent call last):
ChatGPT  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
ChatGPT  |     result = await app(  # type: ignore[func-returns-value]
ChatGPT  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
ChatGPT  |     return await self.app(scope, receive, send)
ChatGPT  |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 271, in __call__
ChatGPT  |     await super().__call__(scope, receive, send)
ChatGPT  |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 125, in __call__
ChatGPT  |     await self.middleware_stack(scope, receive, send)
ChatGPT  |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
ChatGPT  |     raise exc
ChatGPT  |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
ChatGPT  |     await self.app(scope, receive, _send)
ChatGPT  |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
ChatGPT  |     await self.app(scope, receive, send)
ChatGPT  |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
ChatGPT  |     raise exc
ChatGPT  |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
ChatGPT  |     await self.app(scope, receive, sender)
ChatGPT  |   File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
ChatGPT  |     raise e
ChatGPT  |   File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
ChatGPT  |     await self.app(scope, receive, send)
ChatGPT  |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 706, in __call__
ChatGPT  |     await route.handle(scope, receive, send)
ChatGPT  |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
ChatGPT  |     await self.app(scope, receive, send)
ChatGPT  |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
ChatGPT  |     response = await func(request)
ChatGPT  |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
ChatGPT  |     raw_response = await run_endpoint_function(
ChatGPT  |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
ChatGPT  |     return await dependant.call(**values)
ChatGPT  |   File "/app/api/app.py", line 46, in credit_summary
ChatGPT  |     res = await api.credit_summary(api_key=api_key)
ChatGPT  |   File "/app/api/api.py", line 12, in wrapper
ChatGPT  |     raise ValueError('API key is required')
ChatGPT  | ValueError: API key is required

```
这里附上我的Docker-Compose.yml文件：
```
version: "3.8"
services:
  chatgpt:
    image: miclon/chatgpt:latest
    container_name: ChatGPT
    environment:
      - API_KEY=xxxxxx  
    ports:
      - 8000:8000
    restart: always
```

**Comment by mic1on** [comment]
我复制了你的docker-compose.yml内容：

```bash
[+] Running 2/2
 ⠿ Network chatgpt_default  Created                                                                               0.3s
 ⠿ Container ChatGPT        Created                                                                               0.4s
Attaching to ChatGPT
ChatGPT  | app start!
ChatGPT  | INFO:     Started server process [7]
ChatGPT  | INFO:     Waiting for application startup.
ChatGPT  | INFO:     Application startup complete.
ChatGPT  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
```

但是当我打开页面请求`credit_summary`时，出现了你提供的错误。

当前的解决方案是，你打开前端页面。点击红色密钥按钮，输入API_KEY即可。

我会在稍后下个版本中解决这个问题。

**Comment by mic1on** [comment]
已经解决，你可以重新pull镜像后运行：

```bash
docker pull miclon/chatgpt:latest
```

```bash
docker-compose up
```
